<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VignetteAssembly>ParallaxTravelCardsList</VignetteAssembly>
    <ApplicationId>org.avaloniavignettes.parallaxtravelcardslist</ApplicationId>
    <ApplicationTitle>Travel Cards</ApplicationTitle>
  </PropertyGroup>

  <Import Project="../../_hosts/Android/Vignette.Android.props" />

</Project>
