<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VignetteAssembly>SparkleParty</VignetteAssembly>
    <ApplicationId>com.jsuarezruiz.sparkleparty</ApplicationId>
    <ApplicationTitle>Sparkle Party Particles</ApplicationTitle>
  </PropertyGroup>

  <Import Project="../../_hosts/Android/Vignette.Android.props" />

</Project>
