<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VignetteAssembly>ConstellationsList</VignetteAssembly>
    <ApplicationId>com.jsuarezruiz.constellationslist</ApplicationId>
    <ApplicationTitle>Guide To the Stars Particles</ApplicationTitle>
  </PropertyGroup>

  <Import Project="../../_hosts/iOS/Vignette.iOS.props" />

</Project>
