<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VignetteAssembly>BasketballPullToRefresh</VignetteAssembly>
    <ApplicationId>com.jsuarezruiz.basketballpulltorefresh</ApplicationId>
    <ApplicationTitle>Sports App Pull To Refresh</ApplicationTitle>
  </PropertyGroup>

  <Import Project="../../_hosts/iOS/Vignette.iOS.props" />

</Project>
