<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VignetteAssembly>ParallaxTravelCardsHero</VignetteAssembly>
    <ApplicationId>com.jsuarezruiz.parallaxtravelcardshero</ApplicationId>
    <ApplicationTitle>Paris Travel Hero Transition</ApplicationTitle>
  </PropertyGroup>

  <Import Project="../../_hosts/Android/Vignette.Android.props" />

</Project>
