<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VignetteAssembly>ParallaxTravelCardsList</VignetteAssembly>
    <ApplicationId>com.jsuarezruiz.parallaxtravelcardslist</ApplicationId>
    <ApplicationTitle>Travel Cards</ApplicationTitle>
  </PropertyGroup>

  <Import Project="../../_hosts/iOS/Vignette.iOS.props" />

</Project>
