<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VignetteAssembly>FluidNavBar</VignetteAssembly>
    <ApplicationId>com.jsuarezruiz.fluidnavbar</ApplicationId>
    <ApplicationTitle>Fluid Button Bar</ApplicationTitle>
  </PropertyGroup>

  <Import Project="../../_hosts/Android/Vignette.Android.props" />

</Project>
