<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VignetteAssembly>SpendingTracker</VignetteAssembly>
    <ApplicationId>com.jsuarezruiz.spendingtracker</ApplicationId>
    <ApplicationTitle>BudgetTracker Graphs</ApplicationTitle>
  </PropertyGroup>

  <Import Project="../../_hosts/iOS/Vignette.iOS.props" />

</Project>
