<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VignetteAssembly>PlantForms</VignetteAssembly>
    <ApplicationId>com.jsuarezruiz.plantforms</ApplicationId>
    <ApplicationTitle>Plant Shopping Cart</ApplicationTitle>
  </PropertyGroup>

  <Import Project="../../_hosts/Android/Vignette.Android.props" />

</Project>
