<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VignetteAssembly>SparkleParty</VignetteAssembly>
    <ApplicationId>org.avaloniavignettes.sparkleparty</ApplicationId>
    <ApplicationTitle>Sparkle Party Particles</ApplicationTitle>
  </PropertyGroup>

  <Import Project="../../_hosts/iOS/Vignette.iOS.props" />

</Project>
