<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VignetteAssembly>Indie3D</VignetteAssembly>
    <ApplicationId>com.jsuarezruiz.indie3d</ApplicationId>
    <ApplicationTitle>Feature Artist Carousel</ApplicationTitle>
  </PropertyGroup>

  <Import Project="../../_hosts/Android/Vignette.Android.props" />

</Project>
