<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VignetteAssembly>Indie3D</VignetteAssembly>
    <ApplicationId>org.avaloniavignettes.indie3d</ApplicationId>
    <ApplicationTitle>Feature Artist Carousel</ApplicationTitle>
  </PropertyGroup>

  <Import Project="../../_hosts/iOS/Vignette.iOS.props" />

</Project>
