<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VignetteAssembly>DrinkRewardsList</VignetteAssembly>
    <ApplicationId>com.jsuarezruiz.drinkrewardslist</ApplicationId>
    <ApplicationTitle>Liquid Rewards Cards</ApplicationTitle>
  </PropertyGroup>

  <Import Project="../../_hosts/Android/Vignette.Android.props" />

</Project>
