<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VignetteAssembly>GooeyEdge</VignetteAssembly>
    <ApplicationId>com.jsuarezruiz.gooeyedge</ApplicationId>
    <ApplicationTitle>Mindfulness Gooey Transition</ApplicationTitle>
  </PropertyGroup>

  <Import Project="../../_hosts/Android/Vignette.Android.props" />

</Project>
