<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VignetteAssembly>BubbleTabBar</VignetteAssembly>
    <ApplicationId>com.jsuarezruiz.bubbletabbar</ApplicationId>
    <ApplicationTitle>Icon Flip Button Bar</ApplicationTitle>
  </PropertyGroup>

  <Import Project="../../_hosts/Android/Vignette.Android.props" />

</Project>
