<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VignetteAssembly>DarkInkTransition</VignetteAssembly>
    <ApplicationId>com.jsuarezruiz.darkinktransition</ApplicationId>
    <ApplicationTitle>Article Dark Mode</ApplicationTitle>
  </PropertyGroup>

  <Import Project="../../_hosts/Android/Vignette.Android.props" />

</Project>
