<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VignetteAssembly>ParticleSwipe</VignetteAssembly>
    <ApplicationId>com.jsuarezruiz.particleswipe</ApplicationId>
    <ApplicationTitle>Inbox Swipe Particles</ApplicationTitle>
  </PropertyGroup>

  <Import Project="../../_hosts/Android/Vignette.Android.props" />

</Project>
