<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VignetteAssembly>ConstellationsList</VignetteAssembly>
    <ApplicationId>org.avaloniavignettes.constellationslist</ApplicationId>
    <ApplicationTitle>Guide To the Stars Particles</ApplicationTitle>
  </PropertyGroup>

  <Import Project="../../_hosts/Android/Vignette.Android.props" />

</Project>
