<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VignetteAssembly>DrinkRewardsList</VignetteAssembly>
    <ApplicationId>org.avaloniavignettes.drinkrewardslist</ApplicationId>
    <ApplicationTitle>Liquid Rewards Cards</ApplicationTitle>
  </PropertyGroup>

  <Import Project="../../_hosts/iOS/Vignette.iOS.props" />

</Project>
