<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VignetteAssembly>ParticleSwipe</VignetteAssembly>
    <ApplicationId>org.avaloniavignettes.particleswipe</ApplicationId>
    <ApplicationTitle>Inbox Swipe Particles</ApplicationTitle>
  </PropertyGroup>

  <Import Project="../../_hosts/iOS/Vignette.iOS.props" />

</Project>
