<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VignetteAssembly>ProductDetailZoom</VignetteAssembly>
    <ApplicationId>com.jsuarezruiz.productdetailzoom</ApplicationId>
    <ApplicationTitle>Product Zoom Transition</ApplicationTitle>
  </PropertyGroup>

  <Import Project="../../_hosts/iOS/Vignette.iOS.props" />

</Project>
