<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VignetteAssembly>TicketFold</VignetteAssembly>
    <ApplicationId>com.jsuarezruiz.ticketfold</ApplicationId>
    <ApplicationTitle>Boarding Pass Cards</ApplicationTitle>
  </PropertyGroup>

  <Import Project="../../_hosts/Android/Vignette.Android.props" />

</Project>
